/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeetingsIndexRouteImport } from './routes/meetings/index'
import { Route as EventTypesIndexRouteImport } from './routes/event-types/index'
import { Route as AvailabilityIndexRouteImport } from './routes/availability/index'
import { Route as BookSlugIndexRouteImport } from './routes/book/$slug/index'
import { Route as BookSlugConfirmedRouteImport } from './routes/book/$slug/confirmed'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsIndexRoute = MeetingsIndexRouteImport.update({
  id: '/meetings/',
  path: '/meetings/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventTypesIndexRoute = EventTypesIndexRouteImport.update({
  id: '/event-types/',
  path: '/event-types/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityIndexRoute = AvailabilityIndexRouteImport.update({
  id: '/availability/',
  path: '/availability/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugIndexRoute = BookSlugIndexRouteImport.update({
  id: '/book/$slug/',
  path: '/book/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugConfirmedRoute = BookSlugConfirmedRouteImport.update({
  id: '/book/$slug/confirmed',
  path: '/book/$slug/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/availability/': typeof AvailabilityIndexRoute
  '/event-types/': typeof EventTypesIndexRoute
  '/meetings/': typeof MeetingsIndexRoute
  '/book/$slug/confirmed': typeof BookSlugConfirmedRoute
  '/book/$slug/': typeof BookSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityIndexRoute
  '/event-types': typeof EventTypesIndexRoute
  '/meetings': typeof MeetingsIndexRoute
  '/book/$slug/confirmed': typeof BookSlugConfirmedRoute
  '/book/$slug': typeof BookSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/availability/': typeof AvailabilityIndexRoute
  '/event-types/': typeof EventTypesIndexRoute
  '/meetings/': typeof MeetingsIndexRoute
  '/book/$slug/confirmed': typeof BookSlugConfirmedRoute
  '/book/$slug/': typeof BookSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/availability/'
    | '/event-types/'
    | '/meetings/'
    | '/book/$slug/confirmed'
    | '/book/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/availability'
    | '/event-types'
    | '/meetings'
    | '/book/$slug/confirmed'
    | '/book/$slug'
  id:
    | '__root__'
    | '/'
    | '/availability/'
    | '/event-types/'
    | '/meetings/'
    | '/book/$slug/confirmed'
    | '/book/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvailabilityIndexRoute: typeof AvailabilityIndexRoute
  EventTypesIndexRoute: typeof EventTypesIndexRoute
  MeetingsIndexRoute: typeof MeetingsIndexRoute
  BookSlugConfirmedRoute: typeof BookSlugConfirmedRoute
  BookSlugIndexRoute: typeof BookSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/': {
      id: '/meetings/'
      path: '/meetings'
      fullPath: '/meetings/'
      preLoaderRoute: typeof MeetingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-types/': {
      id: '/event-types/'
      path: '/event-types'
      fullPath: '/event-types/'
      preLoaderRoute: typeof EventTypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability/': {
      id: '/availability/'
      path: '/availability'
      fullPath: '/availability/'
      preLoaderRoute: typeof AvailabilityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug/': {
      id: '/book/$slug/'
      path: '/book/$slug'
      fullPath: '/book/$slug/'
      preLoaderRoute: typeof BookSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug/confirmed': {
      id: '/book/$slug/confirmed'
      path: '/book/$slug/confirmed'
      fullPath: '/book/$slug/confirmed'
      preLoaderRoute: typeof BookSlugConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvailabilityIndexRoute: AvailabilityIndexRoute,
  EventTypesIndexRoute: EventTypesIndexRoute,
  MeetingsIndexRoute: MeetingsIndexRoute,
  BookSlugConfirmedRoute: BookSlugConfirmedRoute,
  BookSlugIndexRoute: BookSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
